source 'https://rubygems.org'

ruby '3.3.5'

gem 'rake'

group :test do
  gem 'rspec'
  gem 'nginx_test_helper'
  gem 'em-http-request'
  gem 'byebug'
  gem 'rubyzip', require: 'zip'
  gem 'hiredis-client'
  gem 'redis'
  gem 'ostruct'
  gem 'base64'
end
